global using BuildingBlock.Core.Result;
global using BuildingBlock.CQRS;
global using AutoMapper;
global using BuildingBlock.Core.Request;
global using AutoMapper.QueryableExtensions;
global using BuildingBlock.Core.Abstractions;
global using Microsoft.EntityFrameworkCore;
global using Promotion.API.Constants;
global using Promotion.API.Data; 