global using Catalog.Application.Commons.Interfaces;
global using Catalog.Domain.Entities;
global using Microsoft.EntityFrameworkCore;
global using BuildingBlock.Core.Request;
global using BuildingBlock.Core.Result;
global using BuildingBlock.CQRS;
global using AutoMapper;
global using BuildingBlock.Core.Abstractions;
global using AutoMapper.QueryableExtensions;
